name = "ADIT"
uuid = "214c2b52-412a-43d2-9f52-1f6508573d96"
authors = ["XingyuZhang2018 <864129714@qq.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TeneT = "260a78e0-cbf2-49ba-8157-48058c700f32"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BitBasis = "0.9.6"
ChainRulesCore = "1.25.1"
HDF5 = "0.17.2"
OMEinsum = "=0.7.6"
TeneT = "0.1.1"
Zygote = "=0.6.73"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
